fix syntax

diff --git a/.github/workflows/scrape.yml b/.github/workflows/scrape.yml
--- a/.github/workflows/scrape.yml
+++ b/.github/workflows/scrape.yml
@@ -14,10 +14,10 @@ jobs:
         uses: actions/checkout@v2
       - name: Verify API
         run: |-
-          echo 'API_SUCCESS='$(curl https://api.outbreak.info/genomics/lineage-by-sub-admin-most-recent?location_id=USA&pangolin_lineage=P.1&ndays=60 | jq '.success') >> $GITHUB_ENV
+          echo 'API_SUCCESS='$(curl 'https://api.outbreak.info/genomics/lineage-by-sub-admin-most-recent?location_id=USA&pangolin_lineage=P.1&ndays=60' | jq '.success') >> $GITHUB_ENV
       - name: Fetch latest data
         run: |
-          [[ ${{env.API_SUCCESS}} == "true" ]] && curl 'https://api.outbreak.info/genomics/lineage-by-sub-admin-most-recent?location_id=USA&pangolin_lineage=P.1&ndays=60' > incidents.json || echo "Failed response"
+          [[ ${{ env.API_SUCCESS }} == "true" ]] && curl 'https://api.outbreak.info/genomics/lineage-by-sub-admin-most-recent?location_id=USA&pangolin_lineage=P.1&ndays=60' > incidents.json || echo "Failed response"
       - name: Commit and push if it changed
         run: |-
           git config user.name "Automated"
